env:
  _JAVA_OPTIONS="-Xms1G -Xmx4G"

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - mvn -Dcheckstyle.skip=true clean verify

notifications:
  irc: "chat.freenode.net#io7m"

